shfSecurity:
  index:
    security: false
  logoin:
    security: false
  logout:
    security: true
  noPermission:
    security: false
  exception:
    security: false
    
    
principal:
  index:
    security: true
    credentials:
      - [admin, Bahamon]    
#-------------------modulo - default----------------------------    
default:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, Bahamon]
  create:
    security: true
    credentials:
      - [admin, Bahamon]
  edit: 
    security: true
    credentials:
      - [admin, Bahamon]
  update:
    security: true
    credentials:
      - [admin, Bahamon]
  delete:
    security: true
    credentials:
      - [admin, Bahamon]
  deleteSelect:  
    security: true
    credentials:
      - [admin, Bahamon]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true
    credentials:
      - [admin, consultor]
  
#-------------------modulo - credencial----------------------------  
credencial:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, bahamon]
  create:
    security: true
    credentials:
      - [admin, bahamon]
  edit: 
    security: true
    credentials:
      - [admin, bahamon]
  update:
    security: true
    credentials:
      - [admin, bahamon]
  delete:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelect:  
    security: true
    credentials:
      - [admin]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true  
    credentials:
      - [admin, consultor]
    
#-------------------modulo - usuarioCredencial----------------------------
usuarioCredencial:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, bahamon]
  create:
    security: true
    credentials:
      - [admin, bahamon]
  edit: 
    security: true
    credentials:
      - [admin, bahamon]
  update:
    security: true
    credentials:
      - [admin, bahamon]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true
    credentials:
      - [admin, consultor]

#-------------------modulo - orden servicio-------------------
#-------------------modulo - orden servicio-------------------
ordenServicio:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, bahamon]
  create:
    security: true
    credentials:
      - [admin, bahamon]
  edit: 
    security: true
    credentials:
      - [admin, bahamon]
  update:
    security: true
    credentials:
      - [admin, bahamon]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true
    credentials:
      - [admin, consultor]

#-------------------modulo - maquina--------------------------
maquina:
  indexMaquina:
    security: true
    credentials:
      - [admin, Bahamon]
  insertMaquina:
    security: true
    credentials:
      - [admin, bahamon]
  createMaquina:
    security: true
    credentials:
      - [admin, bahamon]
  editMaquina: 
    security: true
    credentials:
      - [admin, bahamon]
  updateMaquina:
    security: true
    credentials:
      - [admin, bahamon]
  deleteMaquina:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelectMaquina:  
    security: true
    credentials:
      - [admin, bahamon]
  verMaquina:
    security: true
    credentials:
      - [admin, consultor]
  reportMaquina:
    security: true
    credentials:
      - [admin, consultor]
  indexTipoUsoMaquina:
    security: true
    credentials:
      - [admin, Bahamon]
  insertTipoUsoMaquina:
    security: true
    credentials:
      - [admin, bahamon]
  createTipoUsoMaquina:
    security: true
    credentials:
      - [admin, bahamon]
  verTipoUsoMaquina:
    security: true
    credentials:
      - [admin, consultor]
  reportTipoUsoMaquina:
    security: true  
    credentials:
      - [admin, consultor]
  indexProveedor:
    security: true
    credentials:
      - [admin, Bahamon]
  insertProveedor:
    security: true
    credentials:
      - [admin, bahamon]
  createProveedor:
    security: true
    credentials:
      - [admin, bahamon]
  editProveedor: 
    security: true
    credentials:
      - [admin, bahamon]
  updateProveedor:
    security: true
    credentials:
      - [admin, bahamon]
  deleteProveedor:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelectProveedor:  
    security: true
    credentials:
      - [admin, bahamon]
  verProveedor:
    security: true
    credentials:
      - [admin, consultor]
  reportProveedor:
    security: true  
    credentials:
      - [admin, consultor]

#-------------------modulo - origen maquina-------------------
  

#-------------------modulo - tipo uso maquina----------------
  

#-------------------modulo - cliente-------------------------
cliente:
  indexCliente:
    security: true
    credentials:
      - [admin, Bahamon]
  insertCliente:
    security: true
    credentials:
      - [admin, bahamon]
  createCliente:
    security: true
    credentials:
      - [admin, bahamon]
  editCliente: 
    security: true
    credentials:
      - [admin, bahamon]
  updateCliente:
    security: true
    credentials:
      - [admin, bahamon]
  deleteCliente:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelectCliente:  
    security: true
    credentials:
      - [admin, bahamon]
  verCliente:
    security: true
    credentials:
      - [admin, consultor]
  reportCliente:
    security: true
    credentials:
      - [admin, consultor]

#-------------------modulo - lote----------------------------
lote:
  indexLote:
    security: true
    credentials:
      - [admin, Bahamon]
  insertLote:
    security: true
    credentials:
      - [admin, bahamon]
  createLote:
    security: true
    credentials:
      - [admin, bahamon]
  editLote: 
    security: true
    credentials:
      - [admin, bahamon]
  updateLote:
    security: true
    credentials:
      - [admin, bahamon]
  editLoteMas: 
    security: true
    credentials:
      - [admin, bahamon]
  updateLoteMas:
    security: true
    credentials:
      - [admin, bahamon]    
  deleteLote:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelectLote:  
    security: true
    credentials:
      - [admin, bahamon]
  verLote:
    security: true
    credentials:
      - [admin, consultor]
  reportLote:
    security: true
    credentials:
      - [admin, consultor]

#-------------------modulo - tipoProductoInsumo--------------

  

#-------------------modulo - productoInsumo------------------
productoInsumo:
  indexProductoInsumo:
    security: true
    credentials:
      - [admin, Bahamon]
  insertProductoInsumo:
    security: true
    credentials:
      - [admin, bahamon]
  createProductoInsumo:
    security: true
    credentials:
      - [admin, bahamon]
  editProductoInsumo: 
    security: true
    credentials:
      - [admin, bahamon]
  updateProductoInsumo:
    security: true
    credentials:
      - [admin, bahamon]
  deleteProductoInsumo:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelectProductoInsumo:  
    security: true
    credentials:
      - [admin, bahamon]
  verProductoInsumo:
    security: true
    credentials:
      - [admin, consultor]
  reportProductoInsumo:
    security: true
    credentials:
      - [admin, consultor]
  indexTipoProductoInsumo:
    security: true
    credentials:
      - [admin, Bahamon]
  insertTipoProductoInsumo:
    security: true
    credentials:
      - [admin, bahamon]
  createTipoProductoInsumo:
    security: true
    credentials:
      - [admin, bahamon]
  editTipoProductoInsumo: 
    security: true
    credentials:
      - [admin, bahamon]
  updateTipoProductoInsumo:
    security: true
    credentials:
      - [admin, bahamon]
  deleteTipoProductoInsumo:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelectTipoProductoInsumo:  
    security: true
    credentials:
      - [admin, bahamon]
  verTipoProductoInsumo:
    security: true
    credentials:
      - [admin, consultor]
  reportTipoProductoInsumo:
    security: true
    credentials:
      - [admin, consultor]
#-------------------modulo - tipoId--------------------------


#-------------------modulo - solicitud insumo-----------------
solicitudInsumo:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, bahamon]
  create:
    security: true
    credentials:
      - [admin, bahamon]
  edit: 
    security: true
    credentials:
      - [admin, bahamon]
  update:
    security: true
    credentials:
      - [admin, bahamon]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true
    credentials:
      - [admin, consultor]

#-----------------------Pedido-------------------    
pedido:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, bahamon]
  create:
    security: true
    credentials:
      - [admin, bahamon]
  edit: 
    security: true
    credentials:
      - [admin, bahamon]
  update:
    security: true
    credentials:
      - [admin, bahamon]
  delete:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelect:  
    security: true
    credentials:
      - [admin, bahamon]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true 
    credentials:
      - [admin, consultor]  

#-----------------------trabajador-------------------    
trabajador:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, bahamon]
  create:
    security: true
    credentials:
      - [admin, bahamon]
  edit: 
    security: true
    credentials:
      - [admin, bahamon]
  update:
    security: true
    credentials:
      - [admin, bahamon]
  delete:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelect:  
    security: true
    credentials:
      - [admin, bahamon]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true 
    credentials:
      - [admin, consultor]
      
#-----------------------mano de obra-------------------    
manoObra:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, bahamon]
  create:
    security: true
    credentials:
      - [admin, bahamon]
  edit: 
    security: true
    credentials:
      - [admin, bahamon]
  update:
    security: true
    credentials:
      - [admin, bahamon]
  delete:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelect:  
    security: true
    credentials:
      - [admin, bahamon]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true 
    credentials:
      - [admin, consultor]  
      
#-----------------------pago del trabajador-------------------    
pagoTrabajador:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, bahamon]
  create:
    security: true
    credentials:
      - [admin, bahamon]
  edit: 
    security: true
    credentials:
      - [admin, bahamon]
  update:
    security: true
    credentials:
      - [admin, bahamon]
  delete:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelect:  
    security: true
    credentials:
      - [admin, bahamon]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true 
    credentials:
      - [admin, consultor]      
      
#-----------------------cooperativa-------------------
  
cooperativa:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, bahamon]
  create:
    security: true
    credentials:
      - [admin, bahamon]
  edit: 
    security: true
    credentials:
      - [admin, bahamon]
  update:
    security: true
    credentials:
      - [admin, bahamon]
  delete:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelect:  
    security: true
    credentials:
      - [admin]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true  
    credentials:
      - [admin, consultor]
      
#-----------------------empresa-------------------
  
empresa:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, bahamon]
  create:
    security: true
    credentials:
      - [admin, bahamon]
  edit: 
    security: true
    credentials:
      - [admin, bahamon]
  update:
    security: true
    credentials:
      - [admin, bahamon]
  delete:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelect:  
    security: true
    credentials:
      - [admin]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true  
    credentials:
      - [admin, consultor]
      
#-----------------------labor-------------------
  
labor:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, bahamon]
  create:
    security: true
    credentials:
      - [admin, bahamon]
  edit: 
    security: true
    credentials:
      - [admin, bahamon]
  update:
    security: true
    credentials:
      - [admin, bahamon]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true  
    credentials:
      - [admin, consultor]      
      
#-------------------modulo - enfermedad----------------------------  
enfermedad:
  index:
    security: true
    credentials:
      - [admin, Bahamon]
  insert:
    security: true
    credentials:
      - [admin, bahamon]
  create:
    security: true
    credentials:
      - [admin, bahamon]
  edit: 
    security: true
    credentials:
      - [admin, bahamon]
  update:
    security: true
    credentials:
      - [admin, bahamon]
  delete:
    security: true
    credentials:
      - [admin, bahamon]
  deleteSelect:  
    security: true
    credentials:
      - [admin]
  ver:
    security: true
    credentials:
      - [admin, consultor]
  report:
    security: true  
    credentials:
      - [admin, consultor]      