all:
  favicon: hola.ico
  title: titulo de la pagina general
  meta:
    - charset="UTF-8"
  javascript:
    - jquery-1.11.1.min.js
    - bootstrap.js
    - main.js
  stylesheet:
    - bootstrap.css
    - main.css
    - font-awesome.min.css
    
shfSecurity:
  index:
    title: Identificacion de usuario
    stylesheet:
      - signin.css
      
      
   
#-------------------modulo - default----------------------------    
default: 
  index:
    javascript:
      - confirmar.js
  
#-------------------modulo - credencial----------------------------  
credencial: 
  index:
    javascript:
      - confirmar.js
    
#-------------------modulo - usuarioCredencial----------------------------
usuarioCredencial: 
  index:
    javascript:
      - confirmar.js 
      
#-------------------modulo - orden servicio-------------------
ordenServicio: 
  index:
    javascript:
      - confirmar.js

#-------------------modulo - maquina--------------------------
maquina: 
  indexMaquina:
    javascript:
      - confirmar.js
  indexTipoUsoMaquina:
    javascript:
      - confirmar.js 
  indexProveedor:
    javascript:
      - confirmar.js     
#-------------------modulo - origen maquina-------------------

  
      
#-------------------modulo - tipoUsoMaquina------------------

   


#-------------------modulo - cliente-------------------------
cliente: 
  indexCliente:
    javascript:
      - confirmar.js    

#-------------------modulo - lote----------------------------
lote: 
  indexLote:
    javascript:
      - confirmar.js

#-------------------modulo - tipoProductoInsumo--------------
 

#-------------------modulo - productoInsumo------------------
productoInsumo: 
  indexProductoInsumo:
    javascript:
      - confirmar.js 
  indexTipoProductoInsumo:
    javascript:
      - confirmar.js
#-------------------modulo - tipoId-------------------------


#-------------------modulo - solicitud insumo-----------------
solicitudInsumo: 
  index:
    javascript:
      - confirmar.js


#-------------------modulo - Trabajador-----------------------

trabajador: 
  index:
    javascript:
      - confirmar.js
 
#-------------------modulo - Pedido-----------------------
      
pedido: 
  index:
    javascript:
      - confirmar.js
      
#-------------------modulo - Mano de obra-----------------------
      
manoObra: 
  index:
    javascript:
      - confirmar.js 
      
#-------------------modulo - cooperativa-----------------------

cooperativa: 
  index:
    javascript:
      - confirmar.js
      
#-------------------modulo - empresa-----------------------
      
empresa: 
  index:
    javascript:
      - confirmar.js
      
#-------------------modulo - enfermedad-------------------------
enfermedad: 
  index:
    javascript:
      - confirmar.js      
      
       