COMMENT ON SCHEMA public IS NULL;

CREATE SEQUENCE bitacora_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE credencial_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE recordar_me_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE recordar_me_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE usuario_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE usuario_credencial_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE departamento_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE departamento_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE tipo_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE tipo_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE ciudad_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE ciudad_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE cliente_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE cliente_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE lote_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE lote_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE unidad_distancia_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE unidad_distancia_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE tipo_uso_maquina_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE tipo_uso_maquina_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE tipo_producto_insumo_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE tipo_producto_insumo_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE unidad_medida_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE unidad_medida_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE producto_insumo_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE producto_insumo_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE proveedor_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE proveedor_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE trabajador_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE trabajador_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE maquina_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE maquina_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  orden_servicio_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  orden_servicio_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  solicitud_insumo_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  solicitud_insumo_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  labor_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  labor_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  empresa_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  empresa_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  cooperativa_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  cooperativa_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  mano_obra_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  mano_obra_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE pedido_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  pedido_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  pago_trabajador_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  pago_trabajador_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE TABLE bitacora
(
	id BIGINT DEFAULT nextval('public.bitacora_id_seq'::regclass) NOT NULL,
	usuario_id BIGINT NOT NULL,
	accion VARCHAR(80) NOT NULL,
	tabla VARCHAR(80) NOT NULL,
	registro BIGINT NULL,
	observacion VARCHAR(1024) NULL,
	fecha TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE bitacora ADD CONSTRAINT pkbitacora
	PRIMARY KEY (id);

CREATE INDEX "bitacora_fecha_Idx" ON bitacora (fecha);

CREATE INDEX "bitacora_usuario_id_Idx" ON bitacora (usuario_id);

CREATE TABLE credencial
(
	id BIGINT DEFAULT nextval('public.credencial_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(80) NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE credencial ADD CONSTRAINT pkcredencial
	PRIMARY KEY (id);

CREATE TABLE recordar_me
(
	id BIGINT DEFAULT nextval('public.recordar_me_id_seq'::regclass) NOT NULL,
	usuario_id BIGINT NOT NULL,
	ip_address VARCHAR(50) NOT NULL,
	hash_cookie VARCHAR(32) NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE recordar_me ADD CONSTRAINT pkrecordar_me
	PRIMARY KEY (id);

CREATE UNIQUE INDEX "recordar_me_ip_address_hash_cookie_Idx" ON recordar_me (ip_address, hash_cookie);

CREATE INDEX "recordar_me_usuario_id_Idx" ON recordar_me (usuario_id);

CREATE TABLE usuario
(
	id BIGINT DEFAULT nextval('public.usuario_id_seq'::regclass) NOT NULL,
	usuario VARCHAR(80) NOT NULL,
	password VARCHAR(32) NOT NULL,
	actived BOOL DEFAULT 't' NOT NULL,
	last_login_at TIMESTAMP NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE usuario ADD CONSTRAINT pkusuario
	PRIMARY KEY (id);

COMMENT ON COLUMN usuario.actived IS 'TRUE = activado | FALSE = desactivado';

/* Add Indexes */
CREATE INDEX "usuario_actived_Idx" ON usuario (actived);

CREATE INDEX "usuario_deleted_at_Idx" ON usuario (deleted_at);

CREATE UNIQUE INDEX "usuario_user_name_Idx" ON usuario (usuario);

CREATE INDEX "usuario_user_name_password_Idx" ON usuario (usuario, password);

CREATE TABLE departamento
(
	id BIGINT DEFAULT nextval('public.departamento_id_seq'::regclass) NOT NULL,
	nombre_departamento VARCHAR(80) NOT NULL
);

ALTER TABLE departamento ADD CONSTRAINT pkdepartamento
	PRIMARY KEY (id);

CREATE TABLE tipo_id
(
	id BIGINT DEFAULT nextval('public.tipo_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(80) NOT NULL
);

ALTER TABLE tipo_id ADD CONSTRAINT pktipo_id
	PRIMARY KEY (id);	
	
CREATE TABLE ciudad
(
	id BIGINT DEFAULT nextval('public.ciudad_id_seq'::regclass) NOT NULL,
	nombre_ciudad VARCHAR(80) NOT NULL,
	habitantes BigInt NOT NULL,
	departamento_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE ciudad ADD CONSTRAINT pkciudad
	PRIMARY KEY (id);

CREATE TABLE cliente
(
	id BIGINT DEFAULT nextval('public.cliente_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(80) NOT NULL,
	apellido VARCHAR(80) NOT NULL,
	documento BigInt NOT NULL,
	direccion VARCHAR(80) NOT NULL,
	telefono BigInt NOT NULL,
	id_tipo_id BIGINT NOT NULL,
    id_ciudad BIGINT NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE cliente ADD CONSTRAINT pkcliente
	PRIMARY KEY (id);

CREATE TABLE trabajador
(
	id BIGINT DEFAULT nextval('public.trabajador_id_seq'::regclass) NOT NULL,
	nombreT VARCHAR(80) NOT NULL,
	apellido VARCHAR(80) NOT NULL,
	documento BigInt NOT NULL,
	direccion VARCHAR(80) NOT NULL,
	telefono BigInt NOT NULL,
	email VARCHAR(40) NOT NULL,
	id_tipo_id BIGINT NOT NULL,
    id_ciudad BIGINT NOT NULL,
    id_credencial BIGINT NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE trabajador ADD CONSTRAINT pktrabajador
	PRIMARY KEY (id);

CREATE TABLE labor
(
	id BIGINT DEFAULT nextval('public.labor_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(80) NOT NULL,
	valor BigInt NOT NULL,
    created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE labor ADD CONSTRAINT pklabor
	PRIMARY KEY (id);	

CREATE TABLE empresa
(
	id BIGINT DEFAULT nextval('public.empresa_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(80) NOT NULL,
	direccion VARCHAR(80) NOT NULL,
	telefono BigInt NOT NULL,
    email VARCHAR(40) NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE empresa ADD CONSTRAINT pkempresa
	PRIMARY KEY (id);		

CREATE TABLE maquina
(
	id BIGINT DEFAULT nextval('public.maquina_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(80) NOT NULL,
	descripcion VARCHAR(80) NOT NULL,
	origen_maquina VARCHAR(80) NOT NULL,
	id_tipo_uso BIGINT NOT NULL,    
    id_proveedor BIGINT NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE maquina ADD CONSTRAINT pkmaquina
	PRIMARY KEY (id);	

CREATE TABLE producto_insumo
(
	id BIGINT DEFAULT nextval('public.producto_insumo_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(80) NOT NULL,
	iva BigInt NOT NULL,
	unidad_medida_id BIGINT NOT NULL,
	tipo_producto_insumo_id BIGINT NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE producto_insumo ADD CONSTRAINT pkproducto_insumo
	PRIMARY KEY (id);

CREATE TABLE lote
(
	id BIGINT DEFAULT nextval('public.lote_id_seq'::regclass) NOT NULL,
	ubicacion VARCHAR(80) NOT NULL,
	tamano BigInt NOT NULL,
	unidad_distancia_id BIGINT NOT NULL,
	descripcion VARCHAR(80) NOT NULL,		
	fecha_inicio_siembra TIMESTAMP  NULL,
	numero_plantulas BigInt NULL,
	presupuesto VARCHAR(80) NULL,
	producto_insumo_id BIGINT NULL,	
    id_ciudad BIGINT NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE lote ADD CONSTRAINT pklote
	PRIMARY KEY (id);	

CREATE TABLE proveedor
(
	id BIGINT DEFAULT nextval('public.proveedor_id_seq'::regclass) NOT NULL,
	nombreP VARCHAR(80) NOT NULL,
	apellido VARCHAR(80) NOT NULL,
	documento BigInt NOT NULL,
	direccion VARCHAR(80) NOT NULL,
	telefono BigInt NOT NULL,
	email VARCHAR(40) NOT NULL,
    id_ciudad BIGINT NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);


ALTER TABLE proveedor ADD CONSTRAINT pkproveedor
	PRIMARY KEY (id);

CREATE TABLE cooperativa
(
	id BIGINT DEFAULT nextval('public.cooperativa_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(80) NOT NULL,
	descripcion VARCHAR(80) NOT NULL,
	direccion VARCHAR(80) NOT NULL,
	telefono BigInt NOT NULL,
    id_ciudad BIGINT NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE cooperativa ADD CONSTRAINT pkcooperativa
	PRIMARY KEY (id);	

CREATE TABLE orden_servicio
(
	id BIGINT DEFAULT nextval('public.orden_servicio_id_seq'::regclass) NOT NULL,
	fecha_mantenimiento TIMESTAMP DEFAULT now() NOT NULL,
    trabajador_id BIGINT NOT NULL,
    cantidad BigInt NOT NULL,
	valor BigInt NOT NULL,	
    producto_insumo_id BIGINT NOT NULL,
    maquina_id BIGINT NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE orden_servicio ADD CONSTRAINT pkorden_servicio
	PRIMARY KEY (id);	

CREATE TABLE solicitud_insumo
(
	id BIGINT DEFAULT nextval('public.solicitud_insumo_id_seq'::regclass) NOT NULL,
	fecha_hora TIMESTAMP DEFAULT now() NOT NULL,
    trabajador_id BIGINT NOT NULL,	
    cantidad BigInt NOT NULL,	
    producto_insumo_id BIGINT NOT NULL,
    lote_id BIGINT NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE solicitud_insumo ADD CONSTRAINT pksolicitud_insumo
	PRIMARY KEY (id);	

CREATE TABLE pedido
(
	id BIGINT DEFAULT nextval('public.pedido_id_seq'::regclass) NOT NULL,
	empresa_id BIGINT NOT NULL,
    id_proveedor BIGINT NOT NULL,
    cantidad BigInt NOT NULL,	
    producto_insumo_id BIGINT NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE pedido ADD CONSTRAINT pkpedido
	PRIMARY KEY (id);

CREATE TABLE pago_trabajador
(
	id BIGINT DEFAULT nextval('public.pago_trabajador_id_seq'::regclass) NOT NULL,
	fecha_inicial TIMESTAMP DEFAULT now() NOT NULL,
	fecha_final TIMESTAMP DEFAULT now() NOT NULL,
    empresa_id BIGINT NOT NULL,	
    trabajador_id BIGINT NOT NULL,	
	valor_salario BigInt NOT NULL,
	cantidad_horas_extras BigInt NOT NULL,	
	valor_horas_extras BigInt NOT NULL,
    horas_perdidas BigInt NOT NULL,
    total_pagar BigInt NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE pago_trabajador ADD CONSTRAINT pkpago_trabajador
	PRIMARY KEY (id);	

CREATE TABLE mano_obra
(
	id BIGINT DEFAULT nextval('public.mano_obra_id_seq'::regclass) NOT NULL,
	cantidad_hora BigInt NOT NULL,
	valor_hora BigInt NOT NULL,
	cooperativa_id BIGINT NOT NULL,	
    maquina_id BIGINT NOT NULL,
    labor_id BIGINT NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE mano_obra ADD CONSTRAINT pkmano_obra
	PRIMARY KEY (id);

CREATE TABLE tipo_uso_maquina
(
	id BIGINT DEFAULT nextval('public.tipo_uso_maquina_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(80) NOT NULL
);

ALTER TABLE tipo_uso_maquina ADD CONSTRAINT pktipo_uso_maquina
	PRIMARY KEY (id);

CREATE TABLE unidad_medida
(
	id BIGINT DEFAULT nextval('public.unidad_medida_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(80) NOT NULL
);

ALTER TABLE unidad_medida ADD CONSTRAINT pkunidad_medida
	PRIMARY KEY (id);
	
CREATE TABLE unidad_distancia
(
	id BIGINT DEFAULT nextval('public.unidad_distancia_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(80) NOT NULL
);

ALTER TABLE unidad_distancia ADD CONSTRAINT pkunidad_distancia
	PRIMARY KEY (id);	

CREATE TABLE tipo_producto_insumo
(
	id BIGINT DEFAULT nextval('public.tipo_producto_insumo_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(80) NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE tipo_producto_insumo ADD CONSTRAINT pktipo_producto_insumo
	PRIMARY KEY (id);	

CREATE TABLE usuario_credencial
(
	id BIGINT DEFAULT nextval('public.usuario_credencial_id_seq'::regclass) NOT NULL,
	usuario_id BIGINT NOT NULL,
	credencial_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE usuario_credencial ADD CONSTRAINT pkusuario_credencial
	PRIMARY KEY (id);

CREATE INDEX "usuario_credencial_credencial_id_Idx" ON usuario_credencial (credencial_id);

CREATE INDEX "usuario_credencial_usuario_id_Idx" ON usuario_credencial (usuario_id);

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial (usuario_id, credencial_id);

ALTER TABLE bitacora ADD CONSTRAINT fk_bitacora_usuario
	FOREIGN KEY (usuario_id) REFERENCES usuario (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE recordar_me ADD CONSTRAINT fk_recordar_me_usuario
	FOREIGN KEY (usuario_id) REFERENCES usuario (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE usuario_credencial ADD CONSTRAINT fk_usuario_credencial_credencial
	FOREIGN KEY (credencial_id) REFERENCES credencial (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ciudad ADD CONSTRAINT fk_ciudad_departamento
	FOREIGN KEY (departamento_id) REFERENCES departamento (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE cliente ADD CONSTRAINT fk_cliente_ciudad
	FOREIGN KEY (id_ciudad) REFERENCES ciudad (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE cliente ADD CONSTRAINT fk_cliente_tipo_id
	FOREIGN KEY (id_tipo_id) REFERENCES tipo_id (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE lote ADD CONSTRAINT fk_lote_ciudad
	FOREIGN KEY (id_ciudad) REFERENCES ciudad (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE lote ADD CONSTRAINT fk_lote_unidad_distancia
	FOREIGN KEY (unidad_distancia_id) REFERENCES unidad_distancia (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE lote ADD CONSTRAINT fk_lote_producto_insumo
	FOREIGN KEY (producto_insumo_id) REFERENCES producto_insumo (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE producto_insumo ADD CONSTRAINT fk_tipo_producto_insumo_id
	FOREIGN KEY (tipo_producto_insumo_id) REFERENCES tipo_producto_insumo (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE producto_insumo ADD CONSTRAINT fk_unidad_medida_id
	FOREIGN KEY (unidad_medida_id) REFERENCES unidad_medida (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;		

ALTER TABLE proveedor ADD CONSTRAINT fk_proveedor_ciudad
	FOREIGN KEY (id_ciudad) REFERENCES ciudad (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE trabajador ADD CONSTRAINT fk_trabajador_ciudad
	FOREIGN KEY (id_ciudad) REFERENCES ciudad (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE trabajador ADD CONSTRAINT fk_trabajador_tipo_id
	FOREIGN KEY (id_tipo_id) REFERENCES tipo_id (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE maquina ADD CONSTRAINT fk_maquina_tipo_uso_maquina
	FOREIGN KEY (id_tipo_uso) REFERENCES tipo_uso_maquina(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;		

ALTER TABLE maquina ADD CONSTRAINT fk_maquina_proveedor
	FOREIGN KEY (id_proveedor) REFERENCES proveedor(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE solicitud_insumo ADD CONSTRAINT fk_solicitud_insumo_trabajador
	FOREIGN KEY (trabajador_id) REFERENCES trabajador(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE solicitud_insumo ADD CONSTRAINT fk_solicitud_insumo_producto_insumo
	FOREIGN KEY (producto_insumo_id) REFERENCES producto_insumo(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE solicitud_insumo ADD CONSTRAINT fk_solicitud_insumo_lote
	FOREIGN KEY (lote_id) REFERENCES lote(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;		

ALTER TABLE orden_servicio ADD CONSTRAINT fk_orden_servicio_trabajador
	FOREIGN KEY (trabajador_id) REFERENCES trabajador(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE orden_servicio ADD CONSTRAINT fk_orden_servicio_producto_insumo
	FOREIGN KEY (producto_insumo_id) REFERENCES producto_insumo(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE orden_servicio ADD CONSTRAINT fk_orden_servicio_maquina
	FOREIGN KEY (maquina_id) REFERENCES maquina(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE cooperativa ADD CONSTRAINT fk_cooperativa_ciudad
	FOREIGN KEY (id_ciudad) REFERENCES ciudad(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE mano_obra ADD CONSTRAINT fk_mano_obra_labor
	FOREIGN KEY (labor_id) REFERENCES labor(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE mano_obra ADD CONSTRAINT fk_mano_obra_cooperativa
	FOREIGN KEY (cooperativa_id) REFERENCES cooperativa(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE mano_obra ADD CONSTRAINT fk_mano_obra_maquina
	FOREIGN KEY (maquina_id) REFERENCES maquina(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE pedido ADD CONSTRAINT fk_pedido_empresa
	FOREIGN KEY (empresa_id) REFERENCES empresa(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE pedido ADD CONSTRAINT fk_pedido_proveedor
	FOREIGN KEY (id_proveedor) REFERENCES proveedor(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE pedido ADD CONSTRAINT fk_pedido_producto_insumo
	FOREIGN KEY (producto_insumo_id) REFERENCES producto_insumo(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE pago_trabajador ADD CONSTRAINT fk_pago_trabajador_empresa
	FOREIGN KEY (empresa_id) REFERENCES empresa(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;			

ALTER TABLE pago_trabajador ADD CONSTRAINT fk_pago_trabajador_trabajador
	FOREIGN KEY (trabajador_id) REFERENCES trabajador(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;		

ALTER TABLE usuario_credencial ADD CONSTRAINT fk_usuario_credencial_usuario
	FOREIGN KEY (usuario_id) REFERENCES usuario (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

BEGIN;
INSERT INTO "credencial" (nombre) VALUES ('admin');
INSERT INTO "credencial" (nombre) VALUES ('usuario');
COMMIT;

BEGIN;
INSERT INTO "usuario" (usuario, password, actived, last_login_at) VALUES ('admin', '202cb962ac59075b964b07152d234b70', 't', null);
COMMIT;

BEGIN;
INSERT INTO "usuario_credencial" (usuario_id, credencial_id) VALUES (1, 1);
COMMIT;

BEGIN;
INSERT INTO "unidad_distancia" (descripcion) VALUES ('kilometros');
INSERT INTO "unidad_distancia" (descripcion) VALUES ('metros');
COMMIT;

BEGIN;
INSERT INTO "unidad_medida" (descripcion) VALUES ('arroa');
INSERT INTO "unidad_medida" (descripcion) VALUES ('kilogramos');
COMMIT;

BEGIN;
INSERT INTO "departamento" (nombre_departamento) VALUES ('valle del cauca');
INSERT INTO "departamento" (nombre_departamento) VALUES ('cundinamarca');
COMMIT;

BEGIN;
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id ) VALUES ('cali', 12213440, 1);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('pradera', 56000, 1);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('florida', 45000, 1);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('bogota', 23456788, 2);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('buga', 676938, 1);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('tulua', 12209921, 1);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('candelaria', 48000, 1);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('cerrito', 234000, 1);
COMMIT;

BEGIN;
INSERT INTO "tipo_id" (descripcion) VALUES ('cedula');
INSERT INTO "tipo_id" (descripcion) VALUES ('cedula extranjera');
COMMIT;

BEGIN;
INSERT INTO "tipo_uso_maquina" (descripcion) VALUES ('manual');
INSERT INTO "tipo_uso_maquina" (descripcion) VALUES ('automatica');
INSERT INTO "tipo_uso_maquina" (descripcion) VALUES ('semi automatica');
COMMIT;