COMMENT ON SCHEMA public IS NULL;

CREATE SEQUENCE bitacora_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE bitacora_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE credencial_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE credencial_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE recordar_me_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE recordar_me_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE usuario_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE usuario_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE usuario_credencial_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE usuario_credencial_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE departamento_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE departamento_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE tipo_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE tipo_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE ciudad_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE ciudad_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE cliente_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE cliente_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE lote_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE lote_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE unidad_distancia_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE unidad_distancia_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE tipo_uso_maquina_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE tipo_uso_maquina_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE tipo_producto_insumo_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE tipo_producto_insumo_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE unidad_medida_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE unidad_medida_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE producto_insumo_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE producto_insumo_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE proveedor_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE proveedor_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE trabajador_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE trabajador_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE maquina_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE maquina_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  orden_servicio_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  orden_servicio_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  solicitud_insumo_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  solicitud_insumo_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  labor_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  labor_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  empresa_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  empresa_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  cooperativa_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  cooperativa_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  mano_obra_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  mano_obra_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE pedido_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  pedido_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  pago_trabajador_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  pago_trabajador_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  factura_venta_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  factura_venta_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  detalle_factura_venta_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  detalle_factura_venta_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  factura_compra_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  factura_compra_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  detalle_factura_compra_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  detalle_factura_compra_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  historial_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  historial_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  enfermedad_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  enfermedad_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  plaga_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  plaga_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  reporte_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  reporte_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  archivo_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  archivo_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  imagen_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  imagen_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  video_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  video_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE SEQUENCE  registro_lote_id_seq INCREMENT BY 1;
COMMENT ON SEQUENCE  registro_lote_id_seq IS 'DbWrench Autogenerated Sequence.';

CREATE TABLE bitacora
(
	id BIGINT DEFAULT nextval('public.bitacora_id_seq'::regclass) NOT NULL,
	usuario_id BIGINT NOT NULL,
	accion VARCHAR(80) NOT NULL,
	tabla VARCHAR(80) NOT NULL,
	registro BIGINT NULL,
	observacion VARCHAR(1024) NULL,
	fecha TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE bitacora ADD CONSTRAINT pkbitacora
	PRIMARY KEY (id);

CREATE INDEX "bitacora_fecha_Idx" ON bitacora (fecha);

CREATE INDEX "bitacora_usuario_id_Idx" ON bitacora (usuario_id);

CREATE TABLE credencial
(
	id BIGINT DEFAULT nextval('public.credencial_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(80) NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE credencial ADD CONSTRAINT pkcredencial
	PRIMARY KEY (id);

CREATE TABLE recordar_me
(
	id BIGINT DEFAULT nextval('public.recordar_me_id_seq'::regclass) NOT NULL,
	usuario_id BIGINT NOT NULL,
	ip_address VARCHAR(50) NOT NULL,
	hash_cookie VARCHAR(32) NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE recordar_me ADD CONSTRAINT pkrecordar_me
	PRIMARY KEY (id);

CREATE UNIQUE INDEX "recordar_me_ip_address_hash_cookie_Idx" ON recordar_me (ip_address, hash_cookie);

CREATE INDEX "recordar_me_usuario_id_Idx" ON recordar_me (usuario_id);

CREATE TABLE usuario
(
	id BIGINT DEFAULT nextval('public.usuario_id_seq'::regclass) NOT NULL,
	usuario VARCHAR(80) NOT NULL,
	password VARCHAR(32) NOT NULL,
	actived BOOL DEFAULT 't' NOT NULL,
	last_login_at TIMESTAMP NULL,
	nombreImagen VARCHAR(400)  NULL,
	extencionImagen VARCHAR(5)  NULL,
	hashImagen VARCHAR(37)  NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE usuario ADD CONSTRAINT pkusuario
	PRIMARY KEY (id);

COMMENT ON COLUMN usuario.actived IS 'TRUE = activado | FALSE = desactivado';

/* Add Indexes */
CREATE INDEX "usuario_actived_Idx" ON usuario (actived);

CREATE INDEX "usuario_deleted_at_Idx" ON usuario (deleted_at);

CREATE UNIQUE INDEX "usuario_user_name_Idx" ON usuario (usuario);

CREATE INDEX "usuario_user_name_password_Idx" ON usuario (usuario, password);

CREATE TABLE departamento
(
	id BIGINT DEFAULT nextval('public.departamento_id_seq'::regclass) NOT NULL,
	nombre_departamento VARCHAR(80) NOT NULL
);

ALTER TABLE departamento ADD CONSTRAINT pkdepartamento
	PRIMARY KEY (id);

CREATE TABLE tipo_id
(
	id BIGINT DEFAULT nextval('public.tipo_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(80) NOT NULL
);

ALTER TABLE tipo_id ADD CONSTRAINT pktipo_id
	PRIMARY KEY (id);	
	
CREATE TABLE ciudad
(
	id BIGINT DEFAULT nextval('public.ciudad_id_seq'::regclass) NOT NULL,
	nombre_ciudad VARCHAR(80) NOT NULL,
	habitantes BigInt NOT NULL,
	departamento_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE ciudad ADD CONSTRAINT pkciudad
	PRIMARY KEY (id);

CREATE TABLE cliente
(
	id BIGINT DEFAULT nextval('public.cliente_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(80) NOT NULL,
	apellido VARCHAR(80) NOT NULL,
	documento BigInt NOT NULL,
	direccion VARCHAR(400) NOT NULL,
	telefono BigInt NOT NULL,
	id_tipo_id BIGINT NOT NULL,
    id_ciudad BIGINT NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE cliente ADD CONSTRAINT pkcliente
	PRIMARY KEY (id);

CREATE TABLE trabajador
(
	id BIGINT DEFAULT nextval('public.trabajador_id_seq'::regclass) NOT NULL,
	nombreT VARCHAR(80) NOT NULL,
	apellido VARCHAR(80) NOT NULL,
	documento BigInt NOT NULL,
	direccion VARCHAR(400) NOT NULL,
	telefono BigInt NOT NULL,
	email VARCHAR(40) NOT NULL,
	id_tipo_id BIGINT NOT NULL,
    id_ciudad BIGINT NOT NULL,
    id_credencial BIGINT NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE trabajador ADD CONSTRAINT pktrabajador
	PRIMARY KEY (id);

CREATE TABLE labor
(
	id BIGINT DEFAULT nextval('public.labor_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(80) NOT NULL,
	valor BigInt NOT NULL,
    created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE labor ADD CONSTRAINT pklabor
	PRIMARY KEY (id);	

CREATE TABLE empresa
(
	id BIGINT DEFAULT nextval('public.empresa_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(80) NOT NULL,
	direccion VARCHAR(400) NOT NULL,
	telefono BigInt NOT NULL,
    email VARCHAR(40) NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE empresa ADD CONSTRAINT pkempresa
	PRIMARY KEY (id);		

CREATE TABLE maquina
(
	id BIGINT DEFAULT nextval('public.maquina_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(80) NOT NULL,
	descripcion VARCHAR(400) NOT NULL,
	origen_maquina VARCHAR(80) NOT NULL,
	id_tipo_uso BIGINT NOT NULL,    
    id_proveedor BIGINT NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE maquina ADD CONSTRAINT pkmaquina
	PRIMARY KEY (id);	

CREATE TABLE producto_insumo
(
	id BIGINT DEFAULT nextval('public.producto_insumo_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(400) NOT NULL,
	nombreImagen VARCHAR(400)  NULL,
	extencionImagen VARCHAR(5)  NULL,
	hashImagen VARCHAR(37)  NULL,
	tipo_producto_insumo_id BIGINT NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE producto_insumo ADD CONSTRAINT pkproducto_insumo
	PRIMARY KEY (id);

CREATE TABLE lote
(
	id BIGINT DEFAULT nextval('public.lote_id_seq'::regclass) NOT NULL,
	ubicacion VARCHAR(400)  NULL,
	tamano BigInt  NULL,
	unidad_distancia_id BIGINT NULL,
	descripcion VARCHAR(400)  NULL,		
	fecha_inicio_siembra TIMESTAMP NULL,
	fecha_riego TIMESTAMP NULL,
	numero_plantulas BigInt NULL,
	produccion BigInt NULL,
	unidad_medida_id BIGINT NULL,
	presupuesto BIGINT NULL,
	producto_insumo_id BIGINT NULL,	
    id_ciudad BIGINT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE lote ADD CONSTRAINT pklote
	PRIMARY KEY (id);	
	
CREATE TABLE registro_lote
(
	id BIGINT DEFAULT nextval('public.registro_lote_id_seq'::regclass) NOT NULL,
	ubicacion VARCHAR(400)  NULL,
	fecha_riego TIMESTAMP NULL,
	numero_plantulas BigInt NULL,
	produccion BigInt NULL,
	unidad_medida_id BIGINT NULL,
	producto_insumo_id BIGINT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE registro_lote ADD CONSTRAINT pkregistro_lote
	PRIMARY KEY (id);	

CREATE TABLE proveedor
(
	id BIGINT DEFAULT nextval('public.proveedor_id_seq'::regclass) NOT NULL,
	nombreP VARCHAR(80) NOT NULL,
	apellido VARCHAR(80) NOT NULL,
	documento BigInt NOT NULL,
	direccion VARCHAR(400) NOT NULL,
	telefono BigInt NOT NULL,
	email VARCHAR(40) NOT NULL,
    id_ciudad BIGINT NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);


ALTER TABLE proveedor ADD CONSTRAINT pkproveedor
	PRIMARY KEY (id);

CREATE TABLE cooperativa
(
	id BIGINT DEFAULT nextval('public.cooperativa_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(400) NOT NULL,
	descripcion VARCHAR(400) NOT NULL,
	direccion VARCHAR(400) NOT NULL,
	telefono BigInt NOT NULL,
    id_ciudad BIGINT NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE cooperativa ADD CONSTRAINT pkcooperativa
	PRIMARY KEY (id);	

CREATE TABLE orden_servicio
(
	id BIGINT DEFAULT nextval('public.orden_servicio_id_seq'::regclass) NOT NULL,
	fecha_mantenimiento TIMESTAMP DEFAULT now() NOT NULL,
    trabajador_id BIGINT NOT NULL,
    cantidad BigInt NOT NULL,
	valor BigInt NOT NULL,	
    producto_insumo_id BIGINT NOT NULL,
    maquina_id BIGINT NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE orden_servicio ADD CONSTRAINT pkorden_servicio
	PRIMARY KEY (id);	

CREATE TABLE solicitud_insumo
(
	id BIGINT DEFAULT nextval('public.solicitud_insumo_id_seq'::regclass) NOT NULL,
	fecha_hora TIMESTAMP DEFAULT now() NOT NULL,
    trabajador_id BIGINT NOT NULL,	
    cantidad BigInt NOT NULL,	
    producto_insumo_id BIGINT NOT NULL,
    lote_id BIGINT NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE solicitud_insumo ADD CONSTRAINT pksolicitud_insumo
	PRIMARY KEY (id);	

CREATE TABLE pedido
(
	id BIGINT DEFAULT nextval('public.pedido_id_seq'::regclass) NOT NULL,
	empresa_id BIGINT NOT NULL,
    id_proveedor BIGINT NOT NULL,
    cantidad BigInt NOT NULL,	
    producto_insumo_id BIGINT NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE pedido ADD CONSTRAINT pkpedido
	PRIMARY KEY (id);

CREATE TABLE pago_trabajador
(
	id BIGINT DEFAULT nextval('public.pago_trabajador_id_seq'::regclass) NOT NULL,
	fecha_inicial TIMESTAMP DEFAULT now() NOT NULL,
	fecha_final TIMESTAMP DEFAULT now() NOT NULL,
    empresa_id BIGINT NOT NULL,	
    trabajador_id BIGINT NOT NULL,	
	valor_salario BigInt NOT NULL,
	cantidad_horas_extras BigInt NOT NULL,	
	valor_horas_extras BigInt NOT NULL,
    horas_perdidas BigInt NOT NULL,
    total_pagar BigInt NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE pago_trabajador ADD CONSTRAINT pkpago_trabajador
	PRIMARY KEY (id);	

CREATE TABLE mano_obra
(
	id BIGINT DEFAULT nextval('public.mano_obra_id_seq'::regclass) NOT NULL,
	cantidad_hora BigInt NOT NULL,
	valor_hora BigInt NOT NULL,
	total_pagar BigInt NOT NULL,
	cooperativa_id BIGINT NOT NULL,	
    maquina_id BIGINT NOT NULL,
    labor_id BIGINT NOT NULL,	
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE mano_obra ADD CONSTRAINT pkmano_obra
	PRIMARY KEY (id);

CREATE TABLE tipo_uso_maquina
(
	id BIGINT DEFAULT nextval('public.tipo_uso_maquina_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(400) NOT NULL
);

ALTER TABLE tipo_uso_maquina ADD CONSTRAINT pktipo_uso_maquina
	PRIMARY KEY (id);

CREATE TABLE unidad_medida
(
	id BIGINT DEFAULT nextval('public.unidad_medida_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(400) NOT NULL
);

ALTER TABLE unidad_medida ADD CONSTRAINT pkunidad_medida
	PRIMARY KEY (id);
	
CREATE TABLE unidad_distancia
(
	id BIGINT DEFAULT nextval('public.unidad_distancia_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(80) NOT NULL
);

ALTER TABLE unidad_distancia ADD CONSTRAINT pkunidad_distancia
	PRIMARY KEY (id);	

CREATE TABLE tipo_producto_insumo
(
	id BIGINT DEFAULT nextval('public.tipo_producto_insumo_id_seq'::regclass) NOT NULL,
	descripcion VARCHAR(400) NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);

ALTER TABLE tipo_producto_insumo ADD CONSTRAINT pktipo_producto_insumo
	PRIMARY KEY (id);	
	
CREATE TABLE historial
(
	id BIGINT DEFAULT nextval('public.historial_id_seq'::regclass) NOT NULL,
	producto_insumo_id BigInt NOT NULL,
	lote_id BigInt NOT NULL,
	plaga_id BigInt NOT NULL,
    enfermedad_id BIGINT NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE historial ADD CONSTRAINT pkhistorial
	PRIMARY KEY (id);		
	
CREATE TABLE reporte
(
	id BIGINT DEFAULT nextval('public.reporte_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(400) NOT NULL,
	descripcion VARCHAR(400) NOT NULL,	
	direccion VARCHAR(400) NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL
);
ALTER TABLE reporte ADD CONSTRAINT pkreporte
	PRIMARY KEY (id);
CREATE UNIQUE INDEX "reporte_direccion_Idx" ON reporte (direccion);
	
	
CREATE TABLE enfermedad
(
	id BIGINT DEFAULT nextval('public.enfermedad_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(400) NOT NULL,
	descripcion VARCHAR(400) NOT NULL,	
	tratamiento VARCHAR(400) NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP NULL
);
ALTER TABLE enfermedad ADD CONSTRAINT pkenfermedad
	PRIMARY KEY (id);
	
CREATE TABLE plaga
(
	id BIGINT DEFAULT nextval('public.plaga_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(400) NOT NULL,
	descripcion VARCHAR(400) NOT NULL,	
	tratamiento VARCHAR(400) NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL
);
ALTER TABLE plaga ADD CONSTRAINT pkplaga
	PRIMARY KEY (id);	

CREATE TABLE factura_venta
(
	id BIGINT DEFAULT nextval('public.factura_venta_id_seq'::regclass) NOT NULL,
	fecha TIMESTAMP DEFAULT now() NOT NULL,
	trabajador_id BigInt NOT NULL,
	id_cliente BigInt NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE factura_venta ADD CONSTRAINT pkfactura_venta
	PRIMARY KEY (id);	

CREATE TABLE factura_compra
(
	id BIGINT DEFAULT nextval('public.factura_compra_id_seq'::regclass) NOT NULL,
	fecha TIMESTAMP DEFAULT now() NOT NULL,
	id_proveedor BigInt NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE factura_compra ADD CONSTRAINT pkfactura_compra
	PRIMARY KEY (id);	
	
CREATE TABLE detalle_factura_compra
(
	id BIGINT DEFAULT nextval('public.detalle_factura_compra_id_seq'::regclass) NOT NULL,
	producto_insumo_id BigInt NOT NULL,
	cantidad BigInt NOT NULL,	
	valor_unidad BigInt NOT NULL,
	valor_total BigInt NOT NULL,	
	factura_compra_id BigInt NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE detalle_factura_compra ADD CONSTRAINT pkdetalle_factura_compra
	PRIMARY KEY (id);	
	
CREATE TABLE detalle_factura_venta
(
	id BIGINT DEFAULT nextval('public.detalle_factura_venta_id_seq'::regclass) NOT NULL,
	producto_insumo_id BigInt NOT NULL,
	cantidad BigInt NOT NULL,	
	valor_unidad BigInt NOT NULL,
	valor_total BigInt NOT NULL,
	factura_venta_id BigInt NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL,
	updated_at TIMESTAMP DEFAULT now() NOT NULL,
	deleted_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE detalle_factura_venta ADD CONSTRAINT pkdetalle_factura_venta
	PRIMARY KEY (id);	
	
CREATE TABLE archivo
(
	id BIGINT DEFAULT nextval('public.archivo_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(400) NOT NULL,
	extencion VARCHAR(5) NOT NULL,
	hash VARCHAR(37) NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE archivo ADD CONSTRAINT pkarchivo
	PRIMARY KEY (id);
	
CREATE TABLE imagen
(
	id BIGINT DEFAULT nextval('public.imagen_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(400) NOT NULL,
	extencion VARCHAR(5) NOT NULL,
	hash VARCHAR(37) NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE imagen ADD CONSTRAINT pkimagen
	PRIMARY KEY (id);	
	

CREATE TABLE video
(
	id BIGINT DEFAULT nextval('public.video_id_seq'::regclass) NOT NULL,
	nombre VARCHAR(400) NOT NULL,
	extencion VARCHAR(5) NOT NULL,
	hash VARCHAR(37) NOT NULL,		
	created_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE video ADD CONSTRAINT pkvideo
	PRIMARY KEY (id);	
	
	

CREATE TABLE usuario_credencial
(
	id BIGINT DEFAULT nextval('public.usuario_credencial_id_seq'::regclass) NOT NULL,
	usuario_id BIGINT NOT NULL,
	credencial_id BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT now() NOT NULL
);

ALTER TABLE usuario_credencial ADD CONSTRAINT pkusuario_credencial
	PRIMARY KEY (id);

CREATE INDEX "usuario_credencial_credencial_id_Idx" ON usuario_credencial (credencial_id);

CREATE INDEX "usuario_credencial_usuario_id_Idx" ON usuario_credencial (usuario_id);

CREATE UNIQUE INDEX "usuario_credencial_usuario_id_credencial_id_Idx" ON usuario_credencial (usuario_id, credencial_id);

ALTER TABLE bitacora ADD CONSTRAINT fk_bitacora_usuario
	FOREIGN KEY (usuario_id) REFERENCES usuario (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE recordar_me ADD CONSTRAINT fk_recordar_me_usuario
	FOREIGN KEY (usuario_id) REFERENCES usuario (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE usuario_credencial ADD CONSTRAINT fk_usuario_credencial_credencial
	FOREIGN KEY (credencial_id) REFERENCES credencial (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ciudad ADD CONSTRAINT fk_ciudad_departamento
	FOREIGN KEY (departamento_id) REFERENCES departamento (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE cliente ADD CONSTRAINT fk_cliente_ciudad
	FOREIGN KEY (id_ciudad) REFERENCES ciudad (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE cliente ADD CONSTRAINT fk_cliente_tipo_id
	FOREIGN KEY (id_tipo_id) REFERENCES tipo_id (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE lote ADD CONSTRAINT fk_lote_ciudad
	FOREIGN KEY (id_ciudad) REFERENCES ciudad (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE lote ADD CONSTRAINT fk_lote_unidad_distancia
	FOREIGN KEY (unidad_distancia_id) REFERENCES unidad_distancia (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	
	
ALTER TABLE lote ADD CONSTRAINT fk_lote_unidad_medida
	FOREIGN KEY (unidad_medida_id) REFERENCES unidad_medida (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;		

ALTER TABLE lote ADD CONSTRAINT fk_lote_producto_insumo
	FOREIGN KEY (producto_insumo_id) REFERENCES producto_insumo (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE registro_lote ADD CONSTRAINT fk_registro_lote_unidad_medida
	FOREIGN KEY (unidad_medida_id) REFERENCES unidad_medida (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;		

ALTER TABLE registro_lote ADD CONSTRAINT fk_registro_lote_producto_insumo
	FOREIGN KEY (producto_insumo_id) REFERENCES producto_insumo (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE producto_insumo ADD CONSTRAINT fk_tipo_producto_insumo_id
	FOREIGN KEY (tipo_producto_insumo_id) REFERENCES tipo_producto_insumo (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE proveedor ADD CONSTRAINT fk_proveedor_ciudad
	FOREIGN KEY (id_ciudad) REFERENCES ciudad (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE trabajador ADD CONSTRAINT fk_trabajador_ciudad
	FOREIGN KEY (id_ciudad) REFERENCES ciudad (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE trabajador ADD CONSTRAINT fk_trabajador_tipo_id
	FOREIGN KEY (id_tipo_id) REFERENCES tipo_id (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE maquina ADD CONSTRAINT fk_maquina_tipo_uso_maquina
	FOREIGN KEY (id_tipo_uso) REFERENCES tipo_uso_maquina(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;		

ALTER TABLE maquina ADD CONSTRAINT fk_maquina_proveedor
	FOREIGN KEY (id_proveedor) REFERENCES proveedor(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE solicitud_insumo ADD CONSTRAINT fk_solicitud_insumo_trabajador
	FOREIGN KEY (trabajador_id) REFERENCES trabajador(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE solicitud_insumo ADD CONSTRAINT fk_solicitud_insumo_producto_insumo
	FOREIGN KEY (producto_insumo_id) REFERENCES producto_insumo(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE solicitud_insumo ADD CONSTRAINT fk_solicitud_insumo_lote
	FOREIGN KEY (lote_id) REFERENCES lote(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;		

ALTER TABLE orden_servicio ADD CONSTRAINT fk_orden_servicio_trabajador
	FOREIGN KEY (trabajador_id) REFERENCES trabajador(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE orden_servicio ADD CONSTRAINT fk_orden_servicio_producto_insumo
	FOREIGN KEY (producto_insumo_id) REFERENCES producto_insumo(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE orden_servicio ADD CONSTRAINT fk_orden_servicio_maquina
	FOREIGN KEY (maquina_id) REFERENCES maquina(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE cooperativa ADD CONSTRAINT fk_cooperativa_ciudad
	FOREIGN KEY (id_ciudad) REFERENCES ciudad(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE mano_obra ADD CONSTRAINT fk_mano_obra_labor
	FOREIGN KEY (labor_id) REFERENCES labor(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE mano_obra ADD CONSTRAINT fk_mano_obra_cooperativa
	FOREIGN KEY (cooperativa_id) REFERENCES cooperativa(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE mano_obra ADD CONSTRAINT fk_mano_obra_maquina
	FOREIGN KEY (maquina_id) REFERENCES maquina(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE pedido ADD CONSTRAINT fk_pedido_empresa
	FOREIGN KEY (empresa_id) REFERENCES empresa(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE pedido ADD CONSTRAINT fk_pedido_proveedor
	FOREIGN KEY (id_proveedor) REFERENCES proveedor(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE pedido ADD CONSTRAINT fk_pedido_producto_insumo
	FOREIGN KEY (producto_insumo_id) REFERENCES producto_insumo(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE pago_trabajador ADD CONSTRAINT fk_pago_trabajador_empresa
	FOREIGN KEY (empresa_id) REFERENCES empresa(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;			

ALTER TABLE pago_trabajador ADD CONSTRAINT fk_pago_trabajador_trabajador
	FOREIGN KEY (trabajador_id) REFERENCES trabajador(id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	
	
ALTER TABLE factura_compra ADD CONSTRAINT fk_factura_compra_proveedor
	FOREIGN KEY (id_proveedor) REFERENCES proveedor (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	
	
ALTER TABLE detalle_factura_compra ADD CONSTRAINT fk_detalle_factura_compra_factura_compra
	FOREIGN KEY (factura_compra_id) REFERENCES factura_compra (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	
	
ALTER TABLE detalle_factura_compra ADD CONSTRAINT fk_detalle_factura_compra_producto_insumo
	FOREIGN KEY (producto_insumo_id) REFERENCES producto_insumo (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;
	
ALTER TABLE detalle_factura_venta ADD CONSTRAINT fk_detalle_factura_venta_factura_venta
	FOREIGN KEY (factura_venta_id) REFERENCES factura_venta (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	
	
ALTER TABLE factura_venta ADD CONSTRAINT fk_factura_venta_trabajador
	FOREIGN KEY (trabajador_id) REFERENCES trabajador (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;		
	
ALTER TABLE factura_venta ADD CONSTRAINT fk_factura_venta_cliente
	FOREIGN KEY (id_cliente) REFERENCES cliente (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE detalle_factura_venta ADD CONSTRAINT fk_detalle_factura_venta_producto_insumo
	FOREIGN KEY (producto_insumo_id) REFERENCES producto_insumo (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE historial ADD CONSTRAINT fk_historial_producto_insumo
	FOREIGN KEY (producto_insumo_id) REFERENCES producto_insumo (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	
	
ALTER TABLE historial ADD CONSTRAINT fk_historial_enfermedad
	FOREIGN KEY (enfermedad_id) REFERENCES enfermedad (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	
	
ALTER TABLE historial ADD CONSTRAINT fk_historial_plaga
	FOREIGN KEY (plaga_id) REFERENCES plaga (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE historial ADD CONSTRAINT fk_historial_lote
	FOREIGN KEY (lote_id) REFERENCES lote (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;	

ALTER TABLE usuario_credencial ADD CONSTRAINT fk_usuario_credencial_usuario
	FOREIGN KEY (usuario_id) REFERENCES usuario (id)
	ON UPDATE RESTRICT ON DELETE RESTRICT;

BEGIN;
INSERT INTO "credencial" (nombre) VALUES ('admin');
INSERT INTO "credencial" (nombre) VALUES ('consultor');
COMMIT;

BEGIN;
INSERT INTO "usuario" (usuario, password, actived, last_login_at) VALUES ('admin', '202cb962ac59075b964b07152d234b70', 't', null);
COMMIT;

BEGIN;
INSERT INTO "usuario_credencial" (usuario_id, credencial_id) VALUES (1, 1);
COMMIT;

BEGIN;
INSERT INTO "unidad_distancia" (descripcion) VALUES ('kilometros cuadrados');
INSERT INTO "unidad_distancia" (descripcion) VALUES ('metros cuadrados');
COMMIT;

BEGIN;
INSERT INTO "unidad_medida" (descripcion) VALUES ('arroa');
INSERT INTO "unidad_medida" (descripcion) VALUES ('kilogramos');
COMMIT;

BEGIN;
INSERT INTO "departamento" (nombre_departamento) VALUES ('valle del cauca');
INSERT INTO "departamento" (nombre_departamento) VALUES ('cundinamarca');
COMMIT;

BEGIN;
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id ) VALUES ('cali', 12213440, 1);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('pradera', 56000, 1);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('florida', 45000, 1);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('bogota', 23456788, 2);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('buga', 676938, 1);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('tulua', 12209921, 1);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('candelaria', 48000, 1);
INSERT INTO "ciudad" (nombre_ciudad, habitantes, departamento_id) VALUES ('palmira', 234000, 1);
COMMIT;

BEGIN;
INSERT INTO "tipo_id" (descripcion) VALUES ('cedula');
INSERT INTO "tipo_id" (descripcion) VALUES ('cedula extranjera');
COMMIT;

BEGIN;
INSERT INTO "lote" (ubicacion, id_ciudad, tamano, unidad_distancia_id, descripcion) VALUES ('Finca colmenar lote1' , 2, 100, 2, 'lote establecido hace 3 años, 551 arboles');
INSERT INTO "lote" (ubicacion, id_ciudad, tamano, unidad_distancia_id, descripcion) VALUES ('Finca colmenar lote2' , 2, 200, 2, 'lote establecido hace 8 meses, 1632 plantas');
INSERT INTO "lote" (ubicacion, id_ciudad, tamano, unidad_distancia_id, descripcion) VALUES ('Finca colmenar lote3' , 2, 200, 2, 'arboles con promedio de 6 años');
INSERT INTO "lote" (ubicacion, id_ciudad, tamano, unidad_distancia_id, descripcion) VALUES ('Finca colmenar lote4' , 2, 100, 2, 'primera produccion, 1378 plantas');
INSERT INTO "lote" (ubicacion, id_ciudad, tamano, unidad_distancia_id, descripcion) VALUES ('Finca colmenar lote5' , 2, 200, 2, 'otras variedades de frutales');
COMMIT;

BEGIN;
INSERT INTO "tipo_uso_maquina" (descripcion) VALUES ('manual');
INSERT INTO "tipo_uso_maquina" (descripcion) VALUES ('automatica');
INSERT INTO "tipo_uso_maquina" (descripcion) VALUES ('semi automatica');
COMMIT;

BEGIN;
INSERT INTO "proveedor" (documento, nombreP, apellido, email, direccion, id_ciudad, telefono) VALUES (000218372, 'almacen servicampo', 'palmira', 'almacenservicampo@hotmail.com', 'carrera 28 #27-49', 8, 2710080);
INSERT INTO "proveedor" (documento, nombreP, apellido, email, direccion, id_ciudad, telefono) VALUES (29704804, 'Alvaro', 'Hurtado', 'hurtado85@hotmail.com', 'calle 6 #3-03', 2, 2678091);
INSERT INTO "proveedor" (documento, nombreP, apellido, email, direccion, id_ciudad, telefono) VALUES (22322464, 'Carlos Andres', 'Alvares', 'carlosalvares82@gmail.com', 'calle 6 #3-17', 2, 3118716035);
COMMIT;

BEGIN;
INSERT INTO "maquina" (nombre, descripcion, origen_maquina, id_tipo_uso, id_proveedor) VALUES ('guadaña', 'para doble uso de yoyo, cuchilla', 'nueva de almacen', 2, 1);
INSERT INTO "maquina" (nombre, descripcion, origen_maquina, id_tipo_uso, id_proveedor) VALUES ('motosierra', 'espada pequeña, para mantenimiento', 'de segunda, oferta', 1, 2);
INSERT INTO "maquina" (nombre, descripcion, origen_maquina, id_tipo_uso, id_proveedor) VALUES ('despulpadora', 'pequeña en buen estado', 'de segunda, oferta', 1, 2);
COMMIT;

BEGIN;
INSERT INTO "labor" (descripcion, valor) VALUES ('recoleccion cosecha cafe $ * kilo', '450');
INSERT INTO "labor" (descripcion, valor) VALUES ('recoleccion cosecha maracuya $ * kilo', '60');
INSERT INTO "labor" (descripcion, valor) VALUES ('recoleccion cosecha guayaba $ * kilo', '60');
INSERT INTO "labor" (descripcion, valor) VALUES ('control arvenses, plateo en guayaba $ * arbol', '80');
INSERT INTO "labor" (descripcion, valor) VALUES ('semi automatica, plateo en maracuya $ * planta', '35');
COMMIT;

BEGIN;
INSERT INTO "cliente" (documento, id_tipo_id, nombre, apellido, direccion, id_ciudad, telefono) VALUES (6403104, 1, 'Jose Dulmey', 'Sanchez Cardona', 'carrera 3 #5-98', 2, 3113430809);
INSERT INTO "cliente" (documento, id_tipo_id, nombre, apellido, direccion, id_ciudad, telefono) VALUES (29702110, 1, 'Jhaneth Patricia', 'Cardenas Rocha', 'calle 6 #3-03', 2, 3174411822);
INSERT INTO "cliente" (documento, id_tipo_id, nombre, apellido, direccion, id_ciudad, telefono) VALUES (2603744, 1, 'Carlos Alberto', 'Cardenas Tenorio', 'calle 6 #3-17', 2, 3146626885);
COMMIT;

BEGIN;
INSERT INTO "trabajador" (documento, id_tipo_id, nombreT, apellido, email, direccion, id_ciudad, telefono, id_credencial) VALUES (6400699, 1, 'Olver', 'Salazar Avila', 'olversalazar@hotmail.com', 'calle 2b #3-05', 2, 3105292719, 2);
INSERT INTO "trabajador" (documento, id_tipo_id, nombreT, apellido, email, direccion, id_ciudad, telefono, id_credencial) VALUES (6299817, 1, 'Roberto', 'Trujillo Fernandez', 'roberfernandez@hotmail.com', 'finca el colmenar', 2, 3207709777, 2);
INSERT INTO "trabajador" (documento, id_tipo_id, nombreT, apellido, email, direccion, id_ciudad, telefono, id_credencial) VALUES (1114877029, 1,'Jeison Samir', 'Trujillo Cunda', 'jeisoncunda@hotmail.com', 'calle 18a #9a-27 la casilda', 3, 3226467304, 2);
COMMIT;

BEGIN;
INSERT INTO "tipo_producto_insumo" (descripcion) VALUES ('semilla');
INSERT INTO "tipo_producto_insumo" (descripcion) VALUES ('veneno');
INSERT INTO "tipo_producto_insumo" (descripcion) VALUES ('fertilizantes');
COMMIT;

BEGIN;
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('yuca', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('kumquat', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('mandarina arrayana', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('mandarina oneco', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('tangelo minneola', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('tangelo orlando', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('naranja ombligona', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('naranja valencia', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('araza', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('caimo', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('atemoya', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('arbol del pan', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('pomarrosa', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('pitaya amarilla', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('pitaya roja', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('chontaduro', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('mango tommy atkins', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('manga poma', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('mango hilacha', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('manga chancleta', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('mango kent', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('guanabana', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('guama', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('limon pajarito', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('lima acida tahiti', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('limon arrugado', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('platano harton', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('corozo', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('guayaba pera', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('guayaba manzana', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('guayaba indian pink', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('grosella', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('acerola',1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('jaka', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('uvo',1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('cacao', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('uva isabella', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('uva red globe', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('uva italia', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('guayaba coronilla', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('granada', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('zapote', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('platano dominico harton', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('platano cachaco', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('banano gros michel', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('bananito', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('banana', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('maracuya', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('papayo', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('litchi', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('macadamia', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('mangostino', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('durazno', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('nispero japones', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('nispero', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('aguacate hass', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('aguacate trapp', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('aguacate criollo', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('carambolo', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('cafe castillo', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('mamey', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('ciruela', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('madroño', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('mandarina satsuma', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('banano enano', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('papaya comun', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('limon mandarina', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('guayaba peruana', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('icaco', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('choclo dulce', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('choclo', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('mamoncillo', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('habichuela', 1);
INSERT INTO "producto_insumo" (descripcion, tipo_producto_insumo_id) VALUES ('coco', 1);
COMMIT;

BEGIN;
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Cochinillas', 'se caracterizan por tener una especie de escudo protector de colores y consistencias variadas, Se fijan en hojas, ramas y frutos, alimentándose al clavar su pico chupador de savia del vegetal, provocando hojas descoloridas, amarillentas y su posterior caída, Parte de la savia que toman la excretan como líquido azucarado brillante melaza sobre el que se asienta el hongo Negrilla', 'Poda las ramas que estén muy afectadas y pulveriza con un insecticida anti cochinillas Es muy importante tratar cuando haya el mayor número de larvas, ya que de ello depende más del 90% de la eficacia del tratamiento');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Pulgones', 'Los pulgones o Áfidos clavan su pico chupador y absorben savia, deformando hojas y brotes, que se enrollan. Aparece también el hongo Negrilla, de color negro, sobre la melaza que excretan los pulgones, y hormigas que cuidan a éstos', 'Si el ataque es débil, corta las hojas y brotes dañados y dale una ducha con agua jabonosa. Si no, aplica un insecticida antipulgón');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Mosca blanca', 'Son pequeñas moscas de color blanco que se asientan principalmente en el envés de las hojas. Si se agitan salen volando, En frutales ataca mucho a cítricos  naranjo, mandario, limonero', 'Pulverizar con purín de tanaceto puro 100 porciento, el purín se realiza con la planta entera en el momento de floración a razón de 1 kilo gramo  de planta por cada 10 litros de agua, Inhibe la puesta de huevos de la mosca blanca');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Trips', 'Pican las hojas, provocando un color plateado o decoloraciones que luego se secan y caen', 'Normalmente se realizan dos tratamientos químicos espaciados 7 días, Como materias activas destacan el formetanato, aceite de verano, metiocarb, fenitrotión, malatión, naled y acrinatrin. El producto más eficaz es el aceite de verano, el segundo es el formetanato. Con el metiocarb se han generado resistencias');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Araña roja', 'La Araña roja provoca un aspecto amarillento y puntitos amarillos o pardos; luego se abarquillan, se desecan y caen, A veces se aprecian finas telarañas, Plaga típica de verano por calor y sequedad', 'las manchas son muy persistentes y no se van con jabón o detergente hasta pasados varios días se puede tratar con, Clorpirifos, Diazinon, Dimetoato, Etil-azinfos, Paration, Fenitrotion, Fention, Fentoato');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Caracoles', 'También ocasionan daños en árboles frutales, sobre todo en plantaciones de 3 o 4 años Hojas, yemas y brotes, pudiendo matar a árboles jóvenes, En árboles adultos, daña los frutos para exportación y daña la vegetación', 'Además del tratamiento clásico a base de Metaldehido y Mesurol en gránulos o cebos, se pueden colocar láminas de cobre en los troncos de los árboles para que no suban');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Roedores', 'Salen por la noche a buscar alimento como semillas, hortalizas, bayas, raíces, yemas y ramas tiernas, insectos, Además roen la corteza de los árboles', 'Los métodos más efectivos son los cebos anticoagulantes y las trampas pegajosas. Menos eficaces son los sistemas de ultrasonido y las trampas clásicas');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Pájaros', 'Marcas de picoteo en frutos de árbol maduras que se pueden pudrir', 'El clásico muñeco espantapájaros pero cambiándolo de sitio regularmente y con una bolsa en lugar de mano');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Avispas', 'Se alimentan de insectos y arañas, pero en muchos casos llegan a dañar los frutos al ir en busca de sustancias azucaradas', 'Pulverizar con insecticida derribante y localiza y destruye los nidos de avispas');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Mosca de la fruta o Ceratitis', 'La hembra pica en la fruta y pone 6 a 7 huevos, Alrededor de esta picada se produce una decoloración, En frutos aparecen manchas amarillas de 3 a 4 milímetros, Tiende a caerse,Las larvas se alimentan de la pulpa, originando su descomposición y generalmente la caída del fruto', 'Lo normal son pulverizaciones totales con Fenitrotion, Malation o Triclorfon');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Acaro rojo de los frutales', 'Se localizan en el envés y produce decoloraciones. Además la hoja toma color plomizo, Un ataque muy intenso produce defoliación', 'Es fundamental vigilar su presencia, sobre todo en verano, Se obtienen buenos resultados empleando acaricidas, Evitar tratamientos preventivos y alternar materias activas, Mojar bien el árbol');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Orugas de mariposas en frutales', 'La lagarta es un insecto propiamente forestal, pero también ataca a los árboles frutales, devorando hojas, excepto las de la higuera', 'Usa insecticida de ingestión mata a la oruga cuando come la hoja, Los tratamientos se deben repetir cada 10 a 15 días. Pulveriza procurando hacerlo cuando las orugas sean todavía pequeñas, así morirán más fácilmente y no habrán causado daños');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Perforadores de troncos y ramas', ' Las larvas comen la madera de troncos y ramas, Labran galerías y pueden matar al árbol', 'se utilizarán preferentemente Bifentrin, Deltametrin, Fenvalerato, contra adultos o bien Diazinon, Fenitrotion, Metidation o Metil azinfos que tienen buena acción también contra Piojo');
INSERT INTO "plaga" (nombre, descripcion, tratamiento) VALUES ('Broca', 'Cucarron que penetra la almendra en el cafe', 'Re-Re-Re');
COMMIT;

BEGIN;
INSERT INTO "enfermedad" (nombre, descripcion, tratamiento) VALUES ('Oidio o Cenizo en Frutales', 'Es una borra algodonosa blanca o gris en hojas, brotes y frutos', 'Azufre y Dinocap son más preventivos. Mejor son tratamientos específicos antioidios sistémicos que penetran en la hoja Fenarimol, Penconoazol, Nuarimol');
INSERT INTO "enfermedad" (nombre, descripcion, tratamiento) VALUES ('Gymnosporangium sabinae', 'Aparecen unos corpúsculos negros y algo prominentes sobre manchitas rojizas, Ataca a hojas y, a veces, a frutos. Las hojas afectadas se secan y caen', 'se tendrá que realizar un tratamiento a la caída de pétalos con Clortalonil, Folpet, Triforina o Ziram');
INSERT INTO "enfermedad" (nombre, descripcion, tratamiento) VALUES ('Cribado o Perdigonada', 'El síntoma es manchas rojas o marrones en hojas que se desprenden y quedan agujeros redondos', 'se combate con pulverizaciones de Caldo bordelés aplicadas una antes de la floración, otra al cuajar los frutos y la tercera de 10 a 15 días después');
INSERT INTO "enfermedad" (nombre, descripcion, tratamiento) VALUES ('Monilia o Momificado', 'Daña flores, frutos pequeños y ramas, pero el síntomas más claro es la aparición de un micelio gris que provoca la desecación de la flor', 'Los fungicidas que se pueden emplear cuando comienzan a observarse los primero síntomas son Benomilo, Captafol, Captan, Folpet, Iprodiona, Triforina, Vinclozolina, Metiltiofanato, Ziram');
INSERT INTO "enfermedad" (nombre, descripcion, tratamiento) VALUES ('Fusicocum', 'Es abundante y grave, sobre todo en árboles jóvenes muerte de ramas Penetra por la herida que deja la hoja al caer', 'No es fácil su control, Dictiocarbamatos Zineb, Maned o Mancozeb o Cobre a la caída de hoja y tratamiento de invierno con Aceite de invierno');
INSERT INTO "enfermedad" (nombre, descripcion, tratamiento) VALUES ('Mal del plomo', 'La hoja queda color plateado plomizo, La hoja se escrespa y marchita, La planta pierde vitalidad y en casos graves, puede morir', 'No se da tratamiento químico');
INSERT INTO "enfermedad" (nombre, descripcion, tratamiento) VALUES ('Moteado del níspero', 'Ataca a brotes, produciendo manchas, chancros que desecan al brote, El daño más importante es a fruto, donde aparecen manchas oscuras', 'Al podar, suprimir frutos momificados y ramas afectadas, destruyéndolas por fuego');
INSERT INTO "enfermedad" (nombre, descripcion, tratamiento) VALUES ('Fuego bacteriano o Chamuscado', 'El Fuego bacteriano ataca a las ramas jóvenes y a los brotes, los cuales aparecen como quemados y destacan durante el verano', 'Retira las plantas afectadas o poda hasta 60 centímetros más allá del área afectada');
INSERT INTO "enfermedad" (nombre, descripcion, tratamiento) VALUES ('Negrilla', 'Pulgones, Cochinillas y Moscas blancas excretan una sustancia azucarada sobre la que se asienta este hongo llamado comúnmente Negrilla o Mangla', 'Normalmente no se trata directamente. Si se eliminan los insectos anteriores y no aparecerá Se podrían usar caldos cúpricos y más especifícamente, zineb, pero no se suelen usar');
COMMIT;